//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z2_Zadanie
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObiektDoWynajecia : Korytarz
    {
        public string Typ_działalności { get; set; }
        public Nullable<decimal> Cena_wynajmu { get; set; }
        public Nullable<System.DateTime> Data_początku_wynajmu { get; set; }
        public Nullable<System.DateTime> Data_zakończenia_wynajmu { get; set; }
    }
}
