//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z2_Zadanie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parking : Obiekt
    {
        public Nullable<int> Liczba_miejsc_parkingowych { get; set; }
    }
}
